version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "45432:5432"
    environment:
      POSTGRES_PASSWORD: 123321

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
